"""initial schema (sports, leagues, teams, games, ingestion_logs)

Revision ID: 0001
Revises:
Create Date: 2026-09-13

Why this migration exists as a hand-written baseline rather than an
autogenerated diff: the database already has these five tables in it
(created via SQLAlchemy's create_all() during Milestones 1-2), with
real NFL/MLB/NBA data in it. This migration exists to bring that
already-live database under Alembic's version control without
touching a single row -- `alembic stamp 0001` marks an existing DB as
already being at this revision, so nothing gets re-created or
dropped. A fresh database run through `alembic upgrade head` builds
the identical schema from scratch.
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = "0001"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.create_table(
        "sports",
        sa.Column("id", sa.Integer(), primary_key=True),
        sa.Column("name", sa.String(length=50), nullable=False),
        sa.Column("slug", sa.String(length=50), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True)),
        sa.UniqueConstraint("name"),
        sa.UniqueConstraint("slug"),
    )

    op.create_table(
        "leagues",
        sa.Column("id", sa.Integer(), primary_key=True),
        sa.Column("sport_id", sa.Integer(), sa.ForeignKey("sports.id"), nullable=False),
        sa.Column("name", sa.String(length=100), nullable=False),
        sa.Column("slug", sa.String(length=100), nullable=False),
        sa.Column("country", sa.String(length=100)),
        sa.Column("created_at", sa.DateTime(timezone=True)),
        sa.UniqueConstraint("slug"),
    )

    op.create_table(
        "teams",
        sa.Column("id", sa.Integer(), primary_key=True),
        sa.Column("league_id", sa.Integer(), sa.ForeignKey("leagues.id"), nullable=False),
        sa.Column("external_id", sa.String(length=100)),
        sa.Column("provider", sa.String(length=50)),
        sa.Column("name", sa.String(length=150), nullable=False),
        sa.Column("abbreviation", sa.String(length=10)),
        sa.Column("city", sa.String(length=100)),
        sa.Column("venue_name", sa.String(length=150)),
        sa.Column("venue_lat", sa.String(length=50)),
        sa.Column("venue_lon", sa.String(length=50)),
        sa.Column("timezone", sa.String(length=50)),
        sa.Column("active", sa.Boolean(), server_default=sa.true()),
        sa.Column("created_at", sa.DateTime(timezone=True)),
        sa.Column("updated_at", sa.DateTime(timezone=True)),
        sa.UniqueConstraint("league_id", "external_id", "provider"),
    )

    op.create_table(
        "games",
        sa.Column("id", sa.Integer(), primary_key=True),
        sa.Column("league_id", sa.Integer(), sa.ForeignKey("leagues.id"), nullable=False),
        sa.Column("external_id", sa.String(length=100)),
        sa.Column("provider", sa.String(length=50)),
        sa.Column("season", sa.String(length=20)),
        sa.Column("game_date", sa.DateTime(timezone=True), nullable=False),
        sa.Column("home_team_id", sa.Integer(), sa.ForeignKey("teams.id"), nullable=False),
        sa.Column("away_team_id", sa.Integer(), sa.ForeignKey("teams.id"), nullable=False),
        sa.Column("venue_name", sa.String(length=150)),
        sa.Column("status", sa.String(length=30), server_default="scheduled"),
        sa.Column("home_score", sa.Integer()),
        sa.Column("away_score", sa.Integer()),
        sa.Column("overtime", sa.Boolean(), server_default=sa.false()),
        sa.Column("neutral_site", sa.Boolean(), server_default=sa.false()),
        sa.Column("created_at", sa.DateTime(timezone=True)),
        sa.Column("updated_at", sa.DateTime(timezone=True)),
        sa.UniqueConstraint("league_id", "external_id", "provider"),
    )
    op.create_index("idx_games_date", "games", ["game_date"])
    op.create_index("idx_games_teams", "games", ["home_team_id", "away_team_id"])

    op.create_table(
        "ingestion_logs",
        sa.Column("id", sa.Integer(), primary_key=True),
        sa.Column("source", sa.String(length=100), nullable=False),
        sa.Column("stage", sa.String(length=50), nullable=False),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("records_processed", sa.Integer()),
        sa.Column("message", sa.Text()),
        sa.Column("created_at", sa.DateTime(timezone=True)),
    )


def downgrade() -> None:
    op.drop_table("ingestion_logs")
    op.drop_index("idx_games_teams", table_name="games")
    op.drop_index("idx_games_date", table_name="games")
    op.drop_table("games")
    op.drop_table("teams")
    op.drop_table("leagues")
    op.drop_table("sports")
